### ISSUE TITLE
AndroidX Support

### ISSUE THREAD

**Issue by bradmartin** [bradmartin/nativescript-wear-os#16]

**Comment by bradmartin** [comment]
WIP - https://github.com/bradmartin/nativescript-wear-os/tree/androidx

**Comment by bufke** [comment]
Anything I can help out with or test?

**Comment by bradmartin** [comment]
@bufke - thanks for offering. I'm really close to wrapping this up and should have it completed in the next couple of days. I ran into one issue, I don't recall it at the moment. I'll try to run the branch tomorrow and get in touch with the android runtime team at NativeScript to see if they can help resolve it. I want to say it was related to the Static Binding Generator, but, not 100% right now as it's been a week or so since I last started the changes necessary :) will keep you posted.

**Comment by bradmartin** [comment]
Closed via https://github.com/bradmartin/nativescript-wear-os/pull/18
